const routes=['programme','journey','operations','governance','learning','measurement','delivery','evidence'];
const params=new URLSearchParams(location.search);let lang=['en','de','tr'].includes(params.get('lang'))?params.get('lang'):'en';let route=routes.includes(location.hash.slice(1))?location.hash.slice(1):'programme';
let region=0,gates=[false,false,false,false],scenario=0,answers=[null,null,null],handoff=false;
const cohorts=[[40,34,25,20,12,8,5],[30,27,21,17,10,6,4],[30,24,18,12,11,7,4]];
let cost={learners:100,hours:1.5,hourly:40,build:12000,support:2000};
const ui={
 section:T('Section','Bereich','Bölüm'),region:T('Pilot region','Pilotregion','Pilot bölge'),download:T('Export project brief','Projektbrief exportieren','Proje özetini indir'),print:T('Print this view','Ansicht drucken','Görünümü yazdır'),source:T('Source code & history','Quellcode & Verlauf','Kaynak kodu ve geçmiş'),notion:T('Notion project workspace (access required)','Notion-Projektbereich (Zugang erforderlich)','Notion proje alanı (erişim gerekir)'),
 assumption:T('Design assumption','Entwurfsannahme','Tasarım varsayımı'),target:T('Proposed outcome','Vorgeschlagenes Ergebnis','Önerilen sonuç'),owner:T('Owner','Verantwortung','Sorumlu'),touch:T('Touchpoint','Kontaktpunkt','Temas noktası'),pain:T('Pain point hypothesis','Problemhypothese','Sorun varsayımı'),measure:T('Evidence / measure','Nachweis / Messung','Kanıt / ölçüm'),
 common:T('Common core, accountable local adaptation','Gemeinsamer Kern, verantwortliche lokale Anpassung','Ortak çekirdek, sorumlusu belirli yerel uyarlama'),
 blocked:T('Release blocked','Freigabe gesperrt','Yayın engellendi'),allowed:T('Simulated release eligible','Simulierte Freigabe möglich','Simüle yayın koşulları sağlandı'),missing:T('Outstanding checks','Offene Prüfungen','Eksik kontroller'),check:T('Test the release rule','Freigaberegel testen','Yayın kuralını test et'),reset:T('Reset simulation','Simulation zurücksetzen','Simülasyonu sıfırla'),
 correct:T('Appropriate decision','Angemessene Entscheidung','Uygun karar'),incorrect:T('Learning gap identified','Lernlücke erkannt','Öğrenme eksikliği belirlendi'),first:T('First attempt retained','Erstversuch bleibt erhalten','İlk deneme korunur'),record:T('Simulated handoff record','Simulierter Übergabenachweis','Simüle devir kaydı'),pending:T('Pending expert review','Fachprüfung ausstehend','Uzman incelemesi bekliyor'),create:T('Create simulated handoff','Simulierte Übergabe erstellen','Simüle devir oluştur'),role:T('Designated subject expert','Zuständige Fachperson','Yetkili alan uzmanı'),
 learningNote:T('Workflow learning only; no clinical instruction. Decisions are stored in this tab until refresh. Switching language preserves them. No data is transmitted.','Nur Lernen des Ablaufs; keine klinischen Anweisungen. Entscheidungen bleiben bis zum Neuladen in diesem Tab erhalten, auch bei Sprachwechsel. Keine Datenübertragung.','Yalnızca süreç öğrenimi; klinik talimat yok. Kararlar sayfa yenilenene kadar bu sekmede tutulur; dil değişiminde korunur. Veri gönderilmez.'),
 completion:T('Completion is not authorisation. Instructor review has not occurred.','Abschluss ist keine Befugnis. Eine Beurteilung durch Lehrende hat nicht stattgefunden.','Tamamlama yetkilendirme değildir. Eğitici incelemesi yapılmadı.'),
 synthetic:T('SYNTHETIC DATA · EDIT TO EXPLORE','SYNTHETISCHE DATEN · ZUM ERKUNDEN ÄNDERN','SENTETİK VERİ · DEĞİŞTİREREK İNCELE'),
 value:T('Conservative value model','Konservatives Nutzenmodell','İhtiyatlı değer modeli'),valueNote:T('Illustrative assumptions, not realised savings. Potential released time is not cash savings. Adoption is assumed to be 100%; test a lower effective learner count for sensitivity. One-time build cost and annual support are included.','Illustrative Annahmen, keine erzielten Einsparungen. Freiwerdende Zeit ist keine Geldeinsparung. Nutzung wird mit 100% angenommen; für Sensitivität weniger effektive Lernende einsetzen. Einmalige Entwicklung und jährlicher Support sind enthalten.','Örnek varsayımlar; gerçekleşmiş tasarruf değil. Açığa çıkan zaman nakit tasarrufu değildir. Kullanım %100 varsayılır; duyarlılık için etkin katılımcı sayısını azaltın. Tek seferlik geliştirme ve yıllık destek dahil.'),
 costLabels:T(['Effective learners / year','Hours potentially released / learner','Loaded hourly cost (€)','One-time build cost (€)','Annual support (€)'],['Effektive Lernende / Jahr','Potentiell freie Stunden / Person','Vollkosten je Stunde (€)','Einmalige Entwicklung (€)','Jährlicher Support (€)'],['Etkin öğrenen / yıl','Kişi başına potansiyel kazanılan saat','Saatlik toplam maliyet (€)','Tek seferlik geliştirme (€)','Yıllık destek (€)']),
 resultLabels:T(['Potential annual time value','First-year net value','First-year model ROI'],['Potentieller jährlicher Zeitwert','Nettowert im ersten Jahr','Modell-ROI im ersten Jahr'],['Potansiyel yıllık zaman değeri','İlk yıl net değer','İlk yıl model ROI']),
 pilot:T('Pilot & evaluation protocol','Pilot- und Evaluationsprotokoll','Pilot ve değerlendirme protokolü'),
 plan:T('Proposed rollout · not elapsed delivery','Vorgeschlagener Rollout · nicht bereits durchgeführt','Önerilen yaygınlaştırma · tamamlanmış takvim değil'),
 risk:T('Risk','Risiko','Risk'),severity:T('Priority','Priorität','Öncelik'),mitigation:T('Response','Maßnahme','Önlem'),
 capability:T('Role requirement','Anforderung','Rol gerekliliği'),artifact:T('Inspectable evidence','Prüfbarer Nachweis','İncelenebilir kanıt'),open:T('Open','Öffnen','Aç'),
 limits:T('What this project cannot establish','Was dieses Projekt nicht belegt','Bu projenin kanıtlamadığı noktalar'),
 limitsText:T('A degree, years of global corporate experience, actual senior-leadership collaboration, regulated deployment and measured customer outcomes cannot be created by a portfolio simulation. Existing qualifications and real CogOS / Teacherpreneurship leadership belong in the CV with accurate dates and evidence. No ATS score or hiring guarantee is attached to this map.','Abschluss, mehrjährige globale Unternehmenserfahrung, reale Zusammenarbeit mit Führungskräften, regulierter Einsatz und gemessene Kundenergebnisse entstehen nicht durch Simulation. Bestehende Qualifikationen und reale CogOS-/Teacherpreneurship-Leitung gehören mit korrekten Daten in den Lebenslauf. Die Matrix enthält weder ATS-Punktzahl noch Einstellungsgarantie.','Diploma, yıllarca küresel şirket deneyimi, gerçek üst yönetim iş birliği, regüle uygulama ve ölçülmüş müşteri sonuçları portföy simülasyonuyla oluşmaz. Mevcut nitelikler ve gerçek CogOS/Teacherpreneurship liderliği doğru tarihler ve kanıtlarla CV’de yer almalıdır. Bu matris ATS puanı veya işe kabul garantisi içermez.'),
 cv:T('Evidence-based CV wording','Nachweisbasierte CV-Formulierung','Kanıta dayalı CV ifadesi'),
 agenda:T('Weekly review: demonstrate a task → compare acceptance criteria → log feedback → choose the next priority. Monthly steering: scope, dependencies, investment and exception decisions. Regional facilitator handover: objectives, demo, rubric, escalation route and version changes.','Wöchentliches Review: Aufgabe zeigen → Akzeptanzkriterien prüfen → Feedback erfassen → nächste Priorität wählen. Monatlicher Lenkungskreis: Umfang, Abhängigkeiten, Investitionen, Ausnahmen. Regionale Dozentenübergabe: Ziele, Demo, Raster, Eskalation und Versionsänderungen.','Haftalık inceleme: görevi göster → kabul kriterlerini karşılaştır → geri bildirimi kaydet → sonraki önceliği seç. Aylık yönlendirme: kapsam, bağımlılıklar, yatırım ve istisna kararları. Bölgesel eğitici devri: hedefler, demo, rubrik, yönlendirme ve sürüm değişiklikleri.'),
 actual:T('Implementation record · 28 September 2026','Umsetzungsprotokoll · 28. September 2026','Uygulama kaydı · 28 Eylül 2026'),
 actualText:T('Created a three-language programme design and interactive prototype. Notion holds tasks and review status; GitHub holds code versions. Customer validation, domain review and the proposed 12-week rollout remain pending. This is an AI-assisted portfolio build, not evidence of a completed corporate transformation.','Dreisprachigen Programmentwurf und interaktiven Prototyp erstellt. Notion enthält Aufgaben und Prüfstatus, GitHub Codeversionen. Kundenvalidierung, Fachprüfung und der vorgeschlagene 12-Wochen-Rollout stehen aus. KI-unterstützter Portfolioaufbau, kein Nachweis einer abgeschlossenen Unternehmenstransformation.','Üç dilli program tasarımı ve etkileşimli prototip oluşturuldu. Notion görevleri ve inceleme durumunu, GitHub kod sürümlerini tutar. Müşteri doğrulaması, uzman incelemesi ve önerilen 12 haftalık uygulama bekliyor. Bu AI destekli portföy üretimidir; tamamlanmış şirket dönüşümü kanıtı değildir.'),
 sources:T('Sources and framework context','Quellen und Rahmenkontext','Kaynaklar ve çerçeve bağlamı'),
 exportNote:T('The export contains project design and simulation state; it is not a certificate.','Export enthält Entwurf und Simulationsstand; kein Zertifikat.','Dışa aktarım proje tasarımı ve simülasyon durumudur; sertifika değildir.'),
 printNote:T('For the full trilingual documentation use Export project brief in each language.','Für die vollständige dreisprachige Dokumentation den Projektbrief je Sprache exportieren.','Tam üç dilli dokümantasyon için her dilde proje özetini indirin.')
};
const l=x=>x&&typeof x==='object'&&!Array.isArray(x)&&'en'in x?x[lang]:x;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>esc(l(x));
function cell(x){return '<td>'+text(x)+'</td>';}
function table(headers,rows){return '<div class="table-scroll"><table><thead><tr>'+l(headers).map(x=>'<th scope="col">'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(cell).join('')+'</tr>').join('')+'</tbody></table></div>';}
function cards(rows){return '<div class="cards">'+rows.map((r,i)=>'<article class="card"><span class="number">'+String(i+1).padStart(2,'0')+'</span><h3>'+text(r[0])+'</h3><p>'+text(r[1])+'</p></article>').join('')+'</div>';}
function btn(label,attrs=''){return '<button '+attrs+'>'+text(label)+'</button>';}
function heading(title,desc){return '<div class="section-head"><h2 tabindex="-1">'+text(title)+'</h2>'+(desc?'<p>'+text(desc)+'</p>':'')+'</div>';}
function ratio(n,d){return d?100*n/d:null;}
function metrics(a){return [ratio(a[1],a[0]),ratio(a[3],a[2]),ratio(a[2],a[0]),ratio(a[6],a[5]),ratio(a[5],a[4])];}
function model(c){const gross=c.learners*c.hours*c.hourly,total=c.build+c.support;return [gross,gross-total,total?100*(gross-total)/total:null];}
function release(g){return g.every(Boolean);}
function clampCohort(a){a=a.map(x=>Math.max(0,Math.round(Number(x)||0)));a[1]=Math.min(a[1],a[0]);a[2]=Math.min(a[2],a[1]);a[3]=Math.min(a[3],a[2]);a[4]=Math.min(a[4],a[0]);a[5]=Math.min(a[5],a[4]);a[6]=Math.min(a[6],a[5]);return a;}
const percent=n=>n===null?'—':new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(n)+'%';
const money=n=>new Intl.NumberFormat(lang,{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
function navigate(r){route=r;location.hash=r;render();document.querySelector('h2')?.focus();}
function render(){document.documentElement.lang=lang;document.title=l(content.title)+' | Merve Ercan';document.getElementById('brand-title').textContent=l(content.title);document.getElementById('disclosure').textContent=l(content.disclosure);document.getElementById('language').value=lang;
 document.getElementById('nav').innerHTML=routes.map((r,i)=>'<button data-route="'+r+'" '+(r===route?'aria-current="page"':'')+'><span>'+String(i+1).padStart(2,'0')+'</span>'+text(content.nav[i])+'</button>').join('');
 document.getElementById('region-label').textContent=l(ui.region);document.getElementById('region').innerHTML=content.regions.map((r,i)=>'<option value="'+i+'" '+(i===region?'selected':'')+'>'+text(r)+'</option>').join('');
 document.getElementById('export').textContent=l(ui.download);document.getElementById('print').textContent=l(ui.print);document.getElementById('footnote').textContent=l(ui.exportNote);
 let out='';
 if(route==='programme'){out=heading(content.subtitle,content.intro)+'<div class="summary"><div><strong>3</strong><span>'+text(T('learning contexts','Lernkontexte','öğrenme bağlamı'))+'</span></div><div><strong>EN / DE / TR</strong><span>'+text(T('equivalent content','gleichwertige Inhalte','eşdeğer içerik'))+'</span></div><div><strong>12</strong><span>'+text(T('proposed weeks','vorgeschlagene Wochen','önerilen hafta'))+'</span></div></div>'+cards(content.charter)+heading(T('Strategy to outcomes','Von Strategie zu Ergebnissen','Stratejiden sonuçlara'))+table(T(['Business priority','Educational response','Measure'],['Geschäftspriorität','Lernbezogene Antwort','Messung'],['İş önceliği','Eğitim yanıtı','Ölçüm']),content.strategy)+'<p class="callout">'+text(content.context)+'</p>';}
 if(route==='journey'){out=heading(content.nav[1],T('A hypothesis map to validate with customers and service teams. Select a stage to inspect the handoff.','Hypothesenkarte zur Prüfung mit Kunden und Serviceteams. Phase auswählen und Übergabe prüfen.','Müşteri ve servis ekipleriyle doğrulanacak varsayım haritası. Devri incelemek için aşamayı açın.'))+content.journey.map((r,i)=>'<details '+(i===0?'open':'')+'><summary>'+text(r[0])+'</summary><dl>'+[ui.owner,ui.touch,ui.pain,ui.measure].map((h,j)=>'<dt>'+text(h)+'</dt><dd>'+text(r[j+1])+'</dd>').join('')+'</dl></details>').join('')+heading(T('Discovery interview','Bedarfsinterview','İhtiyaç görüşmesi'))+'<ol>'+l(T(['Which service task must a learner perform independently?','Where does the current journey break down? Give a recent example.','Who can approve content and resolve uncertainty?','Which evidence would show readiness beyond completion?','What is the current baseline, source and denominator?'],['Welche Serviceaufgabe muss selbstständig gelingen?','Wo bricht der aktuelle Lernpfad ab? Bitte ein aktuelles Beispiel.','Wer darf Inhalte freigeben und Unsicherheit klären?','Welcher Nachweis zeigt Befähigung über den Abschluss hinaus?','Wie lauten Ausgangswert, Datenquelle und Nenner?'],['Öğrenen hangi servis görevini bağımsız yapmalı?','Mevcut yolculuk nerede aksıyor? Yakın bir örnek verin.','Kim içeriği onaylayabilir ve belirsizliği çözebilir?','Tamamlamanın ötesinde hangi kanıt yetkinliği gösterir?','Başlangıç ölçümü, veri kaynağı ve payda nedir?'])).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol>';}
 if(route==='operations'){out=heading(ui.common,content.adaptations[region])+cards(content.operating)+heading(T('Decision rights · RACI','Entscheidungsrechte · RACI','Karar yetkileri · RACI'))+'<p class="muted">'+text(T('R performs · A accountable · C consulted · I informed. Exactly one A per activity; roles are simulated.','R führt aus · A verantwortlich · C konsultiert · I informiert. Genau ein A je Tätigkeit; simulierte Rollen.','R uygular · A hesap verir · C danışılır · I bilgilendirilir. Her faaliyette tek A; roller simüledir.'))+'</p>'+table(content.raciHeaders,content.raci)+heading(T('Process design','Prozessgestaltung','Süreç tasarımı'))+'<ol class="process">'+l(content.process).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p>'+text(T('Exception: no valid source or responsible reviewer → hold the affected item, preserve the record and route to the coordinator. Proposed educational acknowledgement target: two working days; not a clinical response standard.','Ausnahme: keine gültige Quelle oder zuständige Fachprüfung → betroffenen Inhalt zurückhalten, Datensatz erhalten und Koordination einschalten. Vorgeschlagenes Antwortziel für Lernanfragen: zwei Arbeitstage; kein klinischer Standard.','İstisna: geçerli kaynak veya sorumlu uzman yok → ilgili içeriği beklet, kaydı koru ve koordinatöre yönlendir. Önerilen eğitim talebi alındı bildirimi: iki iş günü; klinik yanıt standardı değil.'))+'</p>';}
 if(route==='governance'){out=heading(content.nav[3],content.gateNote)+'<div class="two-col"><div class="card"><h3>CR-001 / v1.1</h3>'+l(content.gates).map((s,i)=>'<label class="check"><input type="checkbox" data-gate="'+i+'" '+(gates[i]?'checked':'')+'>'+esc(s)+'</label>').join('')+'</div><div class="gate-result '+(release(gates)?'pass':'')+'" role="status"><span class="eyebrow">'+text(T('SIMULATION','SIMULATION','SİMÜLASYON'))+'</span><h3>'+text(release(gates)?ui.allowed:ui.blocked)+'</h3><p>'+text(ui.missing)+': '+gates.filter(x=>!x).length+'</p><p>'+text(release(gates)?T('All four fictional records are present. This does not constitute actual approval.','Alle vier fiktiven Nachweise vorhanden. Dies ist keine tatsächliche Freigabe.','Dört kurgusal kayıt mevcut. Bu gerçek onay değildir.'):T('Keep the affected release pending. Assign missing reviews before considering publication.','Betroffene Freigabe offen halten. Fehlende Prüfungen vor Veröffentlichung zuweisen.','İlgili yayını beklet. Yayımdan önce eksik incelemeleri sorumlulara ata.'))+'</p></div></div>'+heading(T('Change control and conflict resolution','Änderungskontrolle und Konfliktlösung','Değişiklik kontrolü ve çatışma çözümü'))+'<p>'+text(content.governance)+'</p>'+table(T(['Record','Required fields'],['Datensatz','Pflichtfelder'],['Kayıt','Gerekli alanlar']),[
 [T('Source register','Quellenregister','Kaynak kaydı'),T('Source ID, owner, version, supported objective, reviewer, review date, status','Quellen-ID, Verantwortung, Version, Lernziel, Prüfer, Datum, Status','Kaynak kimliği, sahibi, sürümü, hedefi, inceleyen, tarih, durum')],
 [T('Change request','Änderungsantrag','Değişiklik talebi'),T('Requester, affected objective, impact, priority, approval, release and rollback version','Antragsteller, Lernziel, Folgen, Priorität, Freigabe-, Rücksetzversion','Talep eden, hedef, etki, öncelik, onay, yayın ve geri dönüş sürümü')],
 [T('Data minimisation','Datenminimierung','Veri minimizasyonu'),T('Pseudonymous learner ID and learning evidence only. No patient data. Define retention and access before any real pilot.','Nur pseudonyme ID und Lernnachweise. Keine Patientendaten. Aufbewahrung und Zugriff vor realem Pilot festlegen.','Yalnızca takma kimlik ve öğrenme kanıtı. Hasta verisi yok. Gerçek pilot öncesi saklama ve erişim tanımlanmalı.')]
 ]);}
 if(route==='learning'){let s=content.scenarios[scenario];out=heading(content.nav[4],ui.learningNote)+'<div class="pills">'+content.scenarios.map((s,i)=>btn(s.title,'data-scenario="'+i+'" aria-pressed="'+(i===scenario)+'"')).join('')+'</div><div class="card scenario"><span class="eyebrow">'+esc('GSE-L0'+(scenario+1))+'</span><h3>'+text(s.title)+'</h3><p>'+text(s.body)+'</p>'+l(s.choices).map((c,i)=>'<button class="choice" data-answer="'+i+'" '+(answers[scenario]!==null?'disabled':'')+'><b>'+String.fromCharCode(65+i)+'</b>'+esc(c)+'</button>').join('')+(answers[scenario]!==null?'<div class="feedback" role="status"><strong>'+text(answers[scenario]===s.correct?ui.correct:ui.incorrect)+'</strong><p>'+text(s.why)+'</p><small>'+text(ui.first)+'</small></div>':'')+'</div><div class="two-col"><div class="card"><h3>'+text(ui.record)+'</h3><p>'+text(T('Source: GSE-WF-01 v1.0 · fictional workflow specification. Context: selected learning case; unresolved applicability or evidence.','Quelle: GSE-WF-01 v1.0 · fiktive Prozessbeschreibung. Kontext: ausgewählter Lernfall; offene Gültigkeit oder Nachweise.','Kaynak: GSE-WF-01 v1.0 · kurgusal süreç tanımı. Bağlam: seçilen öğrenme vakası; açık uygunluk veya kanıt.'))+'</p>'+btn(ui.create,'id="handoff"')+(handoff?'<p class="feedback">'+text(ui.pending)+' · '+text(ui.role)+'<br>'+text(T('No message sent; simulated record only.','Keine Nachricht gesendet; nur Simulation.','Mesaj gönderilmedi; yalnızca simüle kayıt.'))+'</p>':'')+'</div><div class="card"><h3>'+text(T('Learning evidence','Lernnachweise','Öğrenme kanıtı'))+'</h3><strong class="big">'+answers.filter((a,i)=>a===content.scenarios[i].correct).length+' / 3</strong><p>'+text(T('Appropriate first-attempt decisions','Angemessene Erstentscheidungen','İlk denemede uygun karar'))+' · '+answers.filter(a=>a!==null).length+'/3 '+text(T('attempted','bearbeitet','denendi'))+'</p><p>'+text(ui.completion)+'</p>'+btn(ui.reset,'id="reset-learning"')+'</div></div>';}
 if(route==='measurement'){let a=cohorts[region];out=heading(content.nav[5],content.metricsNote)+'<div class="eyebrow">'+text(ui.synthetic)+'</div><div class="input-grid">'+l(content.metricsLabels).map((label,i)=>'<label>'+esc(label)+'<input type="number" min="0" max="100000" step="1" value="'+a[i]+'" data-cohort="'+i+'"></label>').join('')+'</div><p class="muted">'+text(T('Counts are bounded to their denominators; changing a parent count also bounds dependent counts.','Zähler werden auf ihre Nenner begrenzt; geänderte Oberwerte begrenzen abhängige Werte.','Sayılar paydalarını aşamaz; üst sayı değişince bağlı sayılar da sınırlandırılır.'))+'</p><div class="metrics">'+metrics(a).map((v,i)=>'<article><span>'+esc(l(content.metricNames)[i])+'</span><strong>'+percent(v)+'</strong><div class="bar"><i style="width:'+(v??0)+'%"></i></div><small>'+['completed / assigned','successful / observed','observed / assigned','closed / reassessed','reassessed / initial gaps'][i].split(' / ').map(x=>text(T(x,{completed:'abgeschlossen',assigned:'zugewiesen',successful:'erfolgreich',observed:'beobachtet',closed:'geschlossen',reassessed:'neu bewertet','initial gaps':'Anfangslücken'}[x],{completed:'tamamlayan',assigned:'atanan',successful:'başarılı',observed:'gözlenen',closed:'kapatılan',reassessed:'yeniden değerlendirilen','initial gaps':'ilk eksikler'}[x]))).join(' / ')+'</small></article>').join('')+'</div>'+heading(ui.pilot)+'<p>'+text(content.pilot)+'</p>'+heading(ui.value,ui.valueNote)+'<div class="input-grid">'+Object.keys(cost).map((k,i)=>'<label>'+esc(l(ui.costLabels)[i])+'<input type="number" min="0" max="100000000" step="'+(k==='hours'?'.1':'1')+'" value="'+cost[k]+'" data-cost="'+k+'"></label>').join('')+'</div><div class="metrics">'+model(cost).map((v,i)=>'<article><span>'+esc(l(ui.resultLabels)[i])+'</span><strong>'+(i===2?percent(v):money(v))+'</strong></article>').join('')+'</div><p class="muted">'+text(T('Time value = learners × hours × hourly cost. Net = time value − build − support. ROI = net / (build + support). A zero investment denominator has no defined ROI.','Zeitwert = Lernende × Stunden × Stundensatz. Netto = Zeitwert − Entwicklung − Support. ROI = Netto / (Entwicklung + Support). Bei Investition null ist ROI nicht definiert.','Zaman değeri = öğrenen × saat × saatlik maliyet. Net = zaman değeri − geliştirme − destek. ROI = net / (geliştirme + destek). Sıfır yatırım paydasında ROI tanımsızdır.'))+'</p>';}
 if(route==='delivery'){out=heading(content.nav[6],content.agile)+'<div class="linkbar"><a href="https://app.notion.com/p/3e9215178e8381329c89e6ec38b8472c?pvs=204" target="_blank" rel="noopener">'+text(ui.notion)+' ↗</a></div>'+heading(ui.plan)+content.roadmap.map(r=>'<article class="milestone"><span>'+text(r[0])+'</span><div><h3>'+text(r[1])+'</h3><p>'+text(r[2])+'</p></div></article>').join('')+heading(T('Stakeholder cadence','Stakeholder-Rhythmus','Paydaş çalışma ritmi'))+'<p>'+text(ui.agenda)+'</p>'+heading(T('RAID · initial risks','RAID · anfängliche Risiken','RAID · başlangıç riskleri'))+table(T(['Risk','Priority','Response'],['Risiko','Priorität','Maßnahme'],['Risk','Öncelik','Önlem']),content.risks)+'<p>'+text(T('Dependencies: domain reviewer, regional reviewer, pilot access and LMS owner for future integration. Assumptions: common objectives transfer across contexts. Issues: no real pilot dataset. Decision log: keep expert review despite time pressure.','Abhängigkeiten: Fachprüfung, regionale Prüfung, Pilotzugang, LMS-Verantwortung für spätere Integration. Annahme: gemeinsame Ziele sind übertragbar. Offenes Problem: keine realen Pilotdaten. Entscheidung: Fachprüfung trotz Zeitdruck beibehalten.','Bağımlılıklar: uzman ve bölge inceleyicisi, pilot erişimi, ileride entegrasyon için LMS sahibi. Varsayım: ortak hedefler bağlamlar arasında aktarılır. Açık konu: gerçek pilot verisi yok. Karar: süre baskısında da uzman incelemesini koru.'))+'</p>'+heading(ui.actual)+'<p>'+text(ui.actualText)+'</p>';}
 if(route==='evidence'){out=heading(content.nav[7],T('Trace role requirements to concrete artefacts, not keyword repetition.','Anforderungen mit konkreten Artefakten verknüpfen, nicht mit Wortwiederholung.','Rol gerekliliklerini kelime tekrarına değil somut çıktılara bağla.'))+'<div class="table-scroll"><table><thead><tr><th>'+text(ui.capability)+'</th><th>'+text(ui.artifact)+'</th><th>'+text(ui.open)+'</th></tr></thead><tbody>'+content.evidence.map(r=>'<tr><td>'+esc(r[0])+'</td><td>'+text(r[1])+'</td><td>'+btn(ui.open,'data-route="'+routes[r[2]]+'"')+'</td></tr>').join('')+'</tbody></table></div>'+heading(ui.limits)+'<p>'+text(ui.limitsText)+'</p>'+heading(T('Trend appraisal','Trendbewertung','Trend değerlendirmesi'))+'<p>'+text(content.trends)+'</p>'+heading(ui.cv)+'<blockquote>'+text(content.cv)+'</blockquote><p class="muted">'+text(T('Use after checking the work and its publication. This is a project description, not an ATS score.','Nach Prüfung der Arbeit und Veröffentlichung verwenden. Projektbeschreibung, keine ATS-Punktzahl.','Çalışmayı ve yayını kontrol ettikten sonra kullanın. Proje açıklamasıdır; ATS puanı değildir.'))+'</p>'+heading(ui.sources)+'<ul><li><a href="https://www.siemens-healthineers.com/services/customer-services">Siemens Healthineers Customer Services</a></li><li><a href="https://www.siemens-healthineers.com/en-us/education/hybrid-learning">Hybrid Learning Solutions</a></li><li><a href="https://scrumguides.org/scrum-guide.html">Scrum Guide</a></li><li><a href="https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site">GitHub Pages</a></li></ul><p class="muted">'+text(T('Sources support sector context and framework definitions, not the invented organisation, targets or results.','Quellen stützen Branchenkontext und Rahmenbegriffe, nicht fiktive Organisation, Ziele oder Ergebnisse.','Kaynaklar sektör bağlamını ve çerçeve tanımlarını destekler; kurgusal organizasyon, hedef veya sonuçları değil.'))+'</p><a href="https://github.com/emasworldme/E-learning-Portfolio-1/tree/main/global-service-education" target="_blank" rel="noopener">'+text(ui.source)+' ↗</a>';}
 document.getElementById('view').innerHTML=out;
 document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));
 document.querySelectorAll('[data-gate]').forEach(b=>b.addEventListener('change',()=>{gates[+b.dataset.gate]=b.checked;render();document.querySelector('[data-gate="'+b.dataset.gate+'"]').focus();}));
 document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{scenario=+b.dataset.scenario;render();document.querySelector('[data-scenario="'+scenario+'"]').focus();}));
 document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answers[scenario]===null)answers[scenario]=+b.dataset.answer;render();document.querySelector('.feedback')?.setAttribute('tabindex','-1');document.querySelector('.feedback')?.focus();}));
 document.querySelector('#handoff')?.addEventListener('click',()=>{handoff=true;render();document.querySelector('#handoff').focus();});
 document.querySelector('#reset-learning')?.addEventListener('click',()=>{answers=[null,null,null];handoff=false;render();document.querySelector('#reset-learning').focus();});
 document.querySelectorAll('[data-cohort]').forEach(b=>b.addEventListener('change',()=>{cohorts[region][+b.dataset.cohort]=Math.min(100000,Number(b.value)||0);cohorts[region]=clampCohort(cohorts[region]);render();document.querySelector('[data-cohort="'+b.dataset.cohort+'"]').focus();}));
 document.querySelectorAll('[data-cost]').forEach(b=>b.addEventListener('change',()=>{cost[b.dataset.cost]=Math.max(0,Math.min(1e8,Number(b.value)||0));render();document.querySelector('[data-cost="'+b.dataset.cost+'"]').focus();}));
}
function exportBrief(){const lines=['# '+l(content.title),'Dr. Amine Merve Ercan | 28 September 2026 | v1.0',l(content.disclosure),l(content.context)];
 function add(title,rows){lines.push('\n## '+l(title));rows.forEach(r=>lines.push('- '+r.map(x=>String(l(x))).join(' — ')));}
 add(content.nav[0],content.charter);add(T('Strategy','Strategie','Strateji'),content.strategy);add(content.nav[1],content.journey);add(content.nav[2],content.operating);add('RACI',content.raci);lines.push('\n## '+l(content.nav[3]),l(content.governance),...l(content.gates).map(x=>'- '+x));lines.push('\n## '+l(ui.region),l(content.regions[region]),l(content.adaptations[region]));lines.push('\n## '+l(content.nav[4]),l(ui.learningNote));content.scenarios.forEach(s=>lines.push('### '+l(s.title),l(s.body),...l(s.choices).map((x,i)=>String.fromCharCode(65+i)+'. '+x),l(ui.correct)+': '+String.fromCharCode(65+s.correct),l(s.why)));lines.push('\n## '+l(content.nav[5]),l(content.metricsNote),l(content.pilot),l(ui.valueNote));add(content.nav[6],content.roadmap);lines.push(l(content.agile),l(ui.agenda));add('RAID',content.risks);add(content.nav[7],content.evidence.map(r=>r.slice(0,2)));lines.push(l(content.trends),l(ui.limitsText),'\n## '+l(ui.cv),l(content.cv),'\n'+l(ui.actualText));const blob=new Blob([lines.join('\n\n')],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='GSE_Project_Brief_'+lang.toUpperCase()+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 document.getElementById('language').addEventListener('change',e=>{lang=e.target.value;const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);render();});
 document.getElementById('region').addEventListener('change',e=>{region=+e.target.value;render();});
 document.getElementById('export').addEventListener('click',exportBrief);document.getElementById('print').addEventListener('click',()=>window.print());
 window.addEventListener('hashchange',()=>{const r=location.hash.slice(1);if(routes.includes(r)&&r!==route){route=r;render();}});render();
