const T=(en,de,tr)=>({en,de,tr});
const content={
 title:T('Global Service Education Integration','Globale Integration der Serviceweiterbildung','Küresel Servis Eğitimi Entegrasyonu'),
 subtitle:T('One operating model. Three learning contexts. Three languages.','Ein Betriebsmodell. Drei Lernkontexte. Drei Sprachen.','Tek işletim modeli. Üç öğrenme bağlamı. Üç dil.'),
 disclosure:T('Independent portfolio case · Fictional organisation and data · No Siemens Healthineers affiliation or approval','Unabhängige Portfolio-Fallstudie · Fiktive Organisation und Daten · Keine Verbindung zu oder Freigabe durch Siemens Healthineers','Bağımsız portföy vakası · Kurgusal organizasyon ve veriler · Siemens Healthineers bağlantısı veya onayı yok'),
 intro:T('A strategic integration programme for a fictional global medical-technology service organisation. Explore how business priorities become governed, localised learning journeys and measurable workforce support.','Ein strategisches Integrationsprogramm für eine fiktive globale Medizintechnik-Serviceorganisation. Geschäftsziele werden in gesteuerte, lokalisierte Lernpfade und messbare Unterstützung der Belegschaft übersetzt.','Kurgusal bir küresel medikal teknoloji servis organizasyonu için stratejik entegrasyon programı. İş önceliklerinin, yönetişimi tanımlanmış yerelleştirilmiş öğrenme yolculuklarına ve ölçülebilir iş gücü desteğine dönüşümünü inceleyin.'),
 nav:[T('Programme','Programm','Program'),T('Customer journey','Kundenreise','Müşteri yolculuğu'),T('Operating model','Betriebsmodell','İşletim modeli'),T('Governance lab','Governance-Labor','Yönetişim laboratuvarı'),T('Learning simulation','Lernsimulation','Öğrenme simülasyonu'),T('Measurement','Messung','Ölçüm'),T('Delivery & agile','Umsetzung & Agilität','Uygulama ve agile'),T('Evidence map','Nachweismatrix','Kanıt matrisi')],
 tools:T('Tools & evidence','Werkzeuge & Nachweise','Araçlar ve kanıtlar'),
 context:T('This is a prototype and programme design, not a deployed clinical service. Digital workflow simulations are implemented; immersive VR, LMS integration, customer pilots and regulatory approval are not claimed.','Dies ist ein Prototyp mit Programmentwurf, kein eingesetzter klinischer Dienst. Digitale Ablaufsimulationen sind umgesetzt; immersive VR, LMS-Anbindung, Kundenpiloten und regulatorische Freigaben werden nicht beansprucht.','Bu çalışma prototip ve program tasarımıdır; kullanıma alınmış klinik hizmet değildir. Dijital süreç simülasyonları uygulanmıştır; VR, LMS entegrasyonu, müşteri pilotu veya düzenleyici onay iddia edilmez.'),
 charter:[
 [T('Problem hypothesis','Problemhypothese','Sorun varsayımı'),T('Business lines maintain separate onboarding content; regional teams cannot easily distinguish common requirements from local changes. Completion reports hide unresolved capability gaps. Validate through interviews before investment.','Geschäftsbereiche pflegen getrennte Onboarding-Inhalte; regionale Teams können gemeinsame Anforderungen und lokale Änderungen schwer unterscheiden. Abschlussberichte verdecken offene Kompetenzlücken. Vor Investitionen durch Interviews validieren.','İş birimleri ayrı onboarding içerikleri yönetiyor; bölgeler ortak gerekliliklerle yerel değişiklikleri ayırmakta zorlanıyor. Tamamlama raporları açık yetkinlik eksiklerini gizliyor. Yatırımdan önce görüşmelerle doğrulanmalı.')],
 [T('Programme mandate','Programmauftrag','Programın görevi'),T('Align Educational Design & Operations, three simulated business lines and regional organisations around a common service education lifecycle. Preserve local accountability and expert review.','Educational Design & Operations, drei simulierte Geschäftsbereiche und regionale Organisationen auf einen gemeinsamen Weiterbildungslebenszyklus ausrichten. Lokale Verantwortung und Fachprüfung erhalten.','Educational Design & Operations, üç simüle iş birimi ve bölgesel organizasyonları ortak servis eğitimi yaşam döngüsünde birleştirmek. Yerel sorumluluğu ve uzman incelemesini korumak.')],
 [T('Scope','Umfang','Kapsam'),T('MR onboarding, software-workflow learning and remote-support education; EN/DE/TR delivery; common outcomes, journey, process, release gate, capability dashboard and a proposed 12-week rollout.','MR-Onboarding, Lernen von Softwareabläufen und Weiterbildung zum Remote-Support; EN/DE/TR; gemeinsame Lernziele, Kundenreise, Prozess, Freigabekontrolle, Kompetenzübersicht und vorgeschlagener 12-Wochen-Rollout.','MR onboarding, yazılım iş akışı ve uzaktan destek eğitimi; EN/DE/TR sunum; ortak hedefler, yolculuk, süreç, yayın kontrolü, yetkinlik paneli ve önerilen 12 haftalık yaygınlaştırma.')],
 [T('Boundaries','Abgrenzung','Sınırlar'),T('No patient data, scanner operation, clinical decisions or product claims. Language is independent of region. This case does not demonstrate past employment in a global matrix organisation.','Keine Patientendaten, Scannerbedienung, klinischen Entscheidungen oder Produktversprechen. Sprache und Region sind getrennt. Die Fallstudie belegt keine frühere Beschäftigung in einer globalen Matrixorganisation.','Hasta verisi, cihaz kullanımı, klinik karar veya ürün iddiası yok. Dil bölgeden bağımsızdır. Bu vaka küresel matris organizasyonda geçmiş istihdam deneyimini kanıtlamaz.')]
 ],
 strategy:[
 [T('Workforce readiness','Einsatzbereitschaft','İş gücü hazırlığı'),T('Role-specific pathways and observed task evidence','Rollenspezifische Lernpfade und beobachtete Aufgaben','Role özgü yolculuklar ve gözlenen görev kanıtı'),T('Independent task success; observation coverage','Selbstständiger Aufgabenerfolg; Beobachtungsabdeckung','Bağımsız görev başarısı; gözlem kapsamı')],
 [T('Customer success','Kundenerfolg','Müşteri başarısı'),T('Agree learning outcomes at handover and review gaps after onboarding','Lernziele bei Übergabe vereinbaren und Lücken nach Onboarding prüfen','Devirde öğrenme hedeflerini uzlaştırma ve onboarding sonrası eksikleri inceleme'),T('Time to agreed learning milestone; unresolved questions','Zeit bis zum vereinbarten Lernmeilenstein; offene Fragen','Kararlaştırılan öğrenme hedefine süre; açık sorular')],
 [T('Operational consistency','Betriebliche Einheitlichkeit','Operasyonel tutarlılık'),T('Common source register, release gates and local exceptions','Gemeinsames Quellenregister, Freigaben und lokale Ausnahmen','Ortak kaynak kaydı, yayın kapıları ve yerel istisnalar'),T('Current-version coverage; rework per release','Abdeckung aktueller Versionen; Nacharbeit pro Freigabe','Güncel sürüm kapsamı; yayın başına yeniden iş')],
 [T('Investment discipline','Investitionsdisziplin','Yatırım disiplini'),T('Pilot before scale; prioritise observable performance over activity counts','Vor Skalierung pilotieren; beobachtbare Leistung vor Aktivitätszahlen priorisieren','Ölçeklemeden önce pilot; etkinlik sayısı yerine gözlenebilir performansa öncelik'),T('Cost per reassessed learner; conservative benefit scenarios','Kosten je erneut bewerteter Person; konservative Nutzenszenarien','Yeniden değerlendirilen kişi başına maliyet; ihtiyatlı fayda senaryoları')]
 ],
 journey:[
 [T('01 · Discover','01 · Bedarf erfassen','01 · İhtiyacı keşfet'),T('Customer training lead + service educator','Kundenseitige Weiterbildungsleitung + Service-Dozent','Müşteri eğitim sorumlusu + servis eğitimcisi'),T('Interview and role/task inventory','Interview und Rollen-/Aufgabenübersicht','Görüşme ve rol/görev envanteri'),T('Assumption: generic requests hide different needs','Annahme: allgemeine Anfragen verdecken unterschiedliche Bedarfe','Varsayım: genel talepler farklı ihtiyaçları gizliyor'),T('Approved learning brief with task and baseline','Abgestimmtes Lernbriefing mit Aufgabe und Ausgangswert','Görev ve başlangıç ölçümü içeren uzlaşılan eğitim özeti')],
 [T('02 · Prepare','02 · Vorbereiten','02 · Hazırla'),T('Regional coordinator','Regionale Koordination','Bölgesel koordinatör'),T('Role-specific invitation and prerequisite check','Rollenspezifische Einladung und Voraussetzungen','Role özgü davet ve ön koşul kontrolü'),T('Assumption: responsibilities are unclear','Annahme: Verantwortlichkeiten sind unklar','Varsayım: sorumluluklar belirsiz'),T('Correct pathway selection and prerequisite completion','Passende Lernpfadwahl und erfüllte Voraussetzungen','Doğru yolculuk seçimi ve ön koşulların tamamlanması')],
 [T('03 · Learn','03 · Lernen','03 · Öğren'),T('Learning designer + content owner','Lerndesign + Inhaltsverantwortung','Öğrenme tasarımcısı + içerik sahibi'),T('Digital module, live demonstration, reflective task','Digitales Modul, Live-Demonstration, Reflexionsaufgabe','Dijital modül, canlı gösterim, refleksiyon görevi'),T('Assumption: content overload increases uncertainty','Annahme: Inhaltsfülle erhöht Unsicherheit','Varsayım: içerik yoğunluğu belirsizliği artırıyor'),T('Task accuracy and requests for assistance','Aufgabengenauigkeit und Hilfebedarf','Görev doğruluğu ve yardım ihtiyacı')],
 [T('04 · Apply and escalate','04 · Anwenden und eskalieren','04 · Uygula ve uzmana yönlendir'),T('Learner + designated expert','Lernende + zuständige Fachperson','Öğrenen + yetkili uzman'),T('Decision simulation and contextual handoff','Entscheidungssimulation und kontextbezogene Übergabe','Karar simülasyonu ve bağlamlı devir'),T('Assumption: completion is mistaken for readiness','Annahme: Abschluss wird mit Befähigung verwechselt','Varsayım: tamamlama yetkinlik sanılıyor'),T('Appropriate escalation and complete context','Angemessene Eskalation und vollständiger Kontext','Uygun yönlendirme ve eksiksiz bağlam')],
 [T('05 · Verify','05 · Überprüfen','05 · Doğrula'),T('Authorised assessor','Autorisierte beurteilende Person','Yetkili değerlendirici'),T('Novel task and observation rubric','Neue Aufgabe und Beobachtungsraster','Yeni görev ve gözlem rubriği'),T('Assumption: quiz scores hide transfer gaps','Annahme: Quizwerte verdecken Transferlücken','Varsayım: quiz puanı transfer eksiklerini gizliyor'),T('Observed task success; missing evidence remains visible','Beobachteter Aufgabenerfolg; fehlende Nachweise sichtbar','Gözlenen görev başarısı; eksik kanıt görünür kalır')],
 [T('06 · Sustain','06 · Verstetigen','06 · Sürdür'),T('Customer success lead + education owner','Customer-Success-Leitung + Weiterbildungsverantwortung','Müşteri başarısı sorumlusu + eğitim sahibi'),T('Targeted refresher and 30-day review','Gezielte Auffrischung und 30-Tage-Review','Hedefli tekrar ve 30 günlük inceleme'),T('Assumption: repeated full courses waste effort','Annahme: vollständige Wiederholungskurse binden Ressourcen','Varsayım: tüm kursu tekrarlamak emek kaybı yaratıyor'),T('Reassessment coverage, gap closure and customer feedback','Abdeckung der Neubewertung, Lückenschluss, Kundenfeedback','Yeniden değerlendirme kapsamı, eksik kapatma ve müşteri geri bildirimi')]
 ],
 operating:[
 [T('Global education owner','Globale Weiterbildungsleitung','Küresel eğitim sahibi'),T('Owns portfolio outcomes, priorities and release accountability. Resolves cross-business-line conflicts in a monthly steering review.','Verantwortet Portfolioziele, Prioritäten und Freigaben. Löst bereichsübergreifende Konflikte im monatlichen Lenkungskreis.','Portföy hedefleri, öncelikler ve yayın sorumluluğunu üstlenir. İş birimleri arası çatışmaları aylık yönlendirme toplantısında çözer.')],
 [T('Business-line subject experts','Fachpersonen der Geschäftsbereiche','İş birimi uzmanları'),T('Own technical correctness and version applicability. A business priority cannot override required expert review.','Verantworten fachliche Richtigkeit und Versionsgültigkeit. Geschäftliche Priorität ersetzt keine Fachprüfung.','Teknik doğruluk ve sürüm uygunluğunu sahiplenir. İş önceliği gerekli uzman incelemesini geçersiz kılamaz.')],
 [T('Regional organisations','Regionale Organisationen','Bölgesel organizasyonlar'),T('Own local workflow fit, language review, facilitator preparation and support contacts. Exceptions require documented impact and approval.','Verantworten lokale Abläufe, Sprachprüfung, Dozentenvorbereitung und Supportkontakte. Ausnahmen benötigen dokumentierte Folgen und Freigabe.','Yerel süreç uyumu, dil incelemesi, eğitici hazırlığı ve destek iletişimini sahiplenir. İstisnalar etki kaydı ve onay gerektirir.')],
 [T('Design & Operations','Design & Operations','Tasarım ve Operasyon'),T('Designs modular content, accessibility checks and assessment. Operations manages assignments, completion tracking and release records.','Entwickelt modulare Inhalte, Barrierefreiheitsprüfungen und Bewertungen. Operations verwaltet Zuweisungen, Abschlussverfolgung und Freigabeprotokolle.','Modüler içerik, erişilebilirlik kontrolü ve değerlendirme tasarlar. Operasyon atama, tamamlama takibi ve yayın kayıtlarını yönetir.')]
 ],
 raciHeaders:T(['Decision / activity','Education lead','Designer','Expert','Regional lead','Operations'],['Entscheidung / Tätigkeit','Bildungsleitung','Design','Fachperson','Region','Operations'],['Karar / faaliyet','Eğitim lideri','Tasarımcı','Uzman','Bölge lideri','Operasyon']),
 raci:[
 [T('Set priorities','Prioritäten festlegen','Öncelik belirle'),'A','R','C','C','C'],
 [T('Approve technical content','Fachinhalte freigeben','Teknik içeriği onayla'),'I','R','A','C','I'],
 [T('Approve local adaptation','Lokale Anpassung freigeben','Yerel uyarlamayı onayla'),'C','R','C','A','I'],
 [T('Release approved learning package','Freigegebenes Lernpaket veröffentlichen','Onaylı eğitim paketini yayımla'),'A','C','C','C','R'],
 [T('Review outcome evidence','Ergebnisnachweise prüfen','Sonuç kanıtlarını incele'),'A','R','C','C','R']
 ],
 process:T(['Request and task context','Source/version check','Expert or regional review','Approved release','Delivery and reassessment'],['Anfrage und Aufgabenkontext','Quellen-/Versionsprüfung','Fachliche oder regionale Prüfung','Genehmigte Veröffentlichung','Durchführung und Neubewertung'],['Talep ve görev bağlamı','Kaynak/sürüm kontrolü','Uzman veya bölgesel inceleme','Onaylı yayın','Sunum ve yeniden değerlendirme']),
 regions:[T('Global pilot','Globaler Pilot','Küresel pilot'),T('Germany pilot','Deutschland-Pilot','Almanya pilotu'),T('Türkiye pilot','Türkiye-Pilot','Türkiye pilotu')],
 adaptations:[T('Common objectives and assessment IDs; English working copy; local deployment remains blocked until a responsible region accepts ownership.','Gemeinsame Ziele und Bewertungs-IDs; englische Arbeitsfassung; lokale Einführung erst nach Übernahme durch eine verantwortliche Region.','Ortak hedefler ve değerlendirme kimlikleri; İngilizce çalışma kopyası; sorumlu bölge sahiplenmeden yerel uygulama bekler.'),T('German terminology and facilitator notes; regional workflow review; the same assessment standard. No assumption that language alone satisfies local requirements.','Deutsche Terminologie und Dozentenhinweise; Prüfung regionaler Abläufe; gleicher Bewertungsstandard. Sprache allein erfüllt keine lokalen Anforderungen.','Almanca terimler ve eğitici notları; bölgesel süreç incelemesi; aynı değerlendirme standardı. Yalnızca dil değişimi yerel gereklilikleri karşılamaz.'),T('Turkish terminology and coordinator route; local workflow review; the same assessment standard. Region-specific legal review is not performed in this prototype.','Türkische Terminologie und Koordinationsweg; lokale Prozessprüfung; gleicher Bewertungsstandard. Regionsspezifische Rechtsprüfung wurde nicht durchgeführt.','Türkçe terimler ve koordinatör yönlendirmesi; yerel süreç incelemesi; aynı değerlendirme standardı. Bu prototipte bölgeye özgü hukuki inceleme yapılmadı.')],
 gates:T(['Current source version checked','Technical review recorded','Regional adaptation reviewed','Accessibility and learning QA recorded'],['Aktuelle Quellenversion geprüft','Fachprüfung dokumentiert','Regionale Anpassung geprüft','Barrierefreiheit und Lernqualität geprüft'],['Güncel kaynak sürümü kontrol edildi','Teknik inceleme kaydedildi','Bölgesel uyarlama incelendi','Erişilebilirlik ve öğrenme kalite kontrolü kaydedildi']),
 gateNote:T('Toggle fictional review records to test the decision rule. These are simulated approvals, not real sign-offs. A blocked release routes to the missing owner; no deadline bypass.','Fiktive Prüfnachweise umschalten, um die Entscheidungsregel zu testen. Dies sind simulierte Freigaben. Gesperrte Veröffentlichungen gehen an die fehlende Prüfinstanz; keine Umgehung wegen Termindruck.','Karar kuralını denemek için kurgusal inceleme kayıtlarını işaretleyin. Bunlar gerçek onay değildir. Eksik onay yayını durdurur ve sorumlu role yönlendirilir; son tarih baskısı kontrolü atlatmaz.'),
 governance:T('Change request CR-001: a region asks to shorten onboarding by removing expert review. Decision: reject that removal; offer shorter navigation and targeted refreshers while keeping required evidence. Record impact, owner and version before release. Roll back to the last reviewed version if an error is found.','Änderung CR-001: Eine Region möchte die Fachprüfung streichen, um das Onboarding zu verkürzen. Entscheidung: Streichung ablehnen; kürzere Navigation und gezielte Auffrischung anbieten, erforderliche Nachweise erhalten. Auswirkungen, Zuständigkeit und Version vor Freigabe dokumentieren. Bei Fehlern auf die letzte geprüfte Version zurücksetzen.','Değişiklik CR-001: Bir bölge onboarding süresini azaltmak için uzman incelemesini kaldırmak istiyor. Karar: incelemeyi kaldırmayı reddet; gerekli kanıtları koruyarak kısa gezinme ve hedefli tekrar öner. Yayından önce etki, sorumlu ve sürümü kaydet. Hata bulunursa son incelenen sürüme dön.'),
 scenarios:[
 {title:T('MR onboarding','MR-Onboarding','MR onboarding'),body:T('The course is complete, but the learning record has an unanswered question about the applicable resource. What should happen?','Der Kurs ist abgeschlossen, aber im Lernprotokoll ist eine Frage zur passenden Ressource offen. Was soll geschehen?','Kurs tamamlandı, ancak öğrenme kaydında uygun kaynakla ilgili yanıtlanmamış soru var. Ne yapılmalı?'),choices:T(['Close the question because the course is complete','Keep it pending and send contextual information to the designated expert','Remove the question from the report'],['Frage schließen, weil der Kurs abgeschlossen ist','Offen halten und Kontext an die zuständige Fachperson übergeben','Frage aus dem Bericht entfernen'],['Kurs tamamlandığı için soruyu kapat','Beklemede tut ve bağlamı yetkili uzmana ilet','Soruyu rapordan kaldır']),correct:1,why:T('Completion is not evidence that uncertainty has been resolved. Preserve the gap and assign an accountable reviewer.','Abschluss belegt nicht, dass Unsicherheit geklärt ist. Lücke erhalten und verantwortliche Fachprüfung zuweisen.','Tamamlama, belirsizliğin çözüldüğünü kanıtlamaz. Eksikliği koru ve sorumlu değerlendiriciye yönlendir.')},
 {title:T('Software workflow','Softwareablauf','Yazılım iş akışı'),body:T('A learner opens a guide for version 2 while the fictional training environment uses version 3. No approved mapping is available.','Eine lernende Person öffnet eine Anleitung für Version 2, die fiktive Lernumgebung nutzt Version 3. Eine freigegebene Zuordnung fehlt.','Öğrenen sürüm 2 kılavuzunu açıyor; kurgusal eğitim ortamı sürüm 3 kullanıyor. Onaylı eşleştirme yok.'),choices:T(['Use the older guide without checking','Generate missing instructions automatically','Pause the affected activity and request a version-matched approved source'],['Alte Anleitung ungeprüft verwenden','Fehlende Anleitung automatisch generieren','Betroffene Aktivität pausieren und passende freigegebene Quelle anfordern'],['Eski kılavuzu kontrol etmeden kullan','Eksik talimatları otomatik üret','İlgili etkinliği durdur ve sürüme uygun onaylı kaynak iste']),correct:2,why:T('Source applicability is a release dependency. AI or learner confidence cannot substitute for version review.','Quellengültigkeit ist eine Freigabevoraussetzung. KI oder Selbstvertrauen ersetzen keine Versionsprüfung.','Kaynak uygunluğu yayın ön koşuludur. AI veya öğrenenin özgüveni sürüm incelemesinin yerini tutmaz.')},
 {title:T('Remote-support education','Remote-Support-Schulung','Uzaktan destek eğitimi'),body:T('An educator receives a recurring learning question without the module ID, version or previous steps. What improves the handoff?','Eine wiederkehrende Lernfrage geht ohne Modul-ID, Version oder bisherige Schritte ein. Was verbessert die Übergabe?','Eğitimciye modül kimliği, sürüm veya önceki adımlar olmadan tekrarlanan bir öğrenme sorusu geliyor. Devir nasıl iyileşir?'),choices:T(['Capture module, version and attempted steps; route to the designated role','Mark the learner as competent','Forward an empty ticket to every department'],['Modul, Version und bisherige Schritte erfassen; zuständig zuweisen','Person als kompetent markieren','Leeres Ticket an alle Abteilungen senden'],['Modül, sürüm ve denenen adımları kaydet; sorumlu role ilet','Öğreneni yetkin olarak işaretle','Boş talebi tüm birimlere gönder']),correct:0,why:T('A structured service handoff reduces clarification loops. It remains an educational query, not a clinical escalation system.','Strukturierte Übergabe reduziert Rückfrageschleifen. Es bleibt eine Lernfrage, kein klinisches Eskalationssystem.','Yapılandırılmış servis devri açıklama döngülerini azaltmayı hedefler. Bu eğitim sorusudur; klinik yönlendirme sistemi değildir.')}
 ],
 metricsLabels:T(['Assigned','Completed','Observed','Successful','Initial gaps','Reassessed gaps','Closed gaps'],['Zugewiesen','Abgeschlossen','Beobachtet','Erfolgreich','Anfangslücken','Neu bewertet','Geschlossene Lücken'],['Atanan','Tamamlayan','Gözlenen','Başarılı','İlk eksikler','Yeniden değerlendirilen','Kapatılan eksikler']),
 metricNames:T(['Completion rate','Observed task success','Observation coverage','Gap closure','Reassessment coverage'],['Abschlussquote','Beobachteter Aufgabenerfolg','Beobachtungsabdeckung','Lückenschluss','Neubewertungsabdeckung'],['Tamamlama oranı','Gözlenen görev başarısı','Gözlem kapsamı','Eksik kapatma','Yeniden değerlendirme kapsamı']),
 metricsNote:T('Synthetic cohorts only. Success is successful / observed, not successful / completed. Gap closure is closed / reassessed; show reassessment coverage alongside it. No before/after causal effect is claimed.','Nur synthetische Gruppen. Erfolg = erfolgreich / beobachtet, nicht erfolgreich / abgeschlossen. Lückenschluss = geschlossen / neu bewertet; Abdeckung mitanzeigen. Kein kausaler Vorher-Nachher-Effekt wird behauptet.','Yalnızca sentetik gruplar. Başarı = başarılı / gözlenen; başarılı / tamamlayan değil. Eksik kapatma = kapatılan / yeniden değerlendirilen; kapsamıyla birlikte gösterilir. Önce-sonra nedensel etki iddia edilmez.'),
 pilot:T('Proposed pilot: 8–12 consenting adult volunteers complete fictional learning tasks. Record assistance, first-attempt accuracy, task time and qualitative confusion. Test a revised version with participant overlap disclosed. At 30 days use a new task if feasible. Targets: ≥80% unassisted task success and no unresolved critical usability defect. Targets are not achieved results; convenience sampling and practice effects limit inference.','Vorgeschlagener Pilot: 8–12 einwilligende Erwachsene bearbeiten fiktive Lernaufgaben. Hilfe, Erstversuchsgenauigkeit, Zeit und Unklarheiten erfassen. Überarbeitete Version testen und wiederholte Teilnahme offenlegen. Nach 30 Tagen möglichst eine neue Aufgabe. Ziele: ≥80% selbstständiger Erfolg und keine offenen kritischen Bedienprobleme. Keine erzielten Ergebnisse; Gelegenheitsstichprobe und Übungseffekte begrenzen Aussagen.','Önerilen pilot: 8–12 gönüllü yetişkin kurgusal görevleri tamamlar. Yardım, ilk deneme doğruluğu, süre ve karışıklıklar kaydedilir. Düzeltilen sürüm tekrar katılanlar belirtilerek test edilir. Mümkünse 30 gün sonra yeni görev uygulanır. Hedef: ≥%80 yardımsız başarı ve açık kritik kullanılabilirlik hatası olmaması. Bunlar gerçekleşmiş sonuç değildir; uygun örneklem ve alıştırma etkisi çıkarımı sınırlar.'),
 roadmap:[
 [T('Weeks 1–2','Woche 1–2','Hafta 1–2'),T('Discover & align','Erfassen & abstimmen','Keşfet ve hizala'),T('Interview guide, capability baseline, stakeholder map and signed scope. Gate: sponsor agrees outcomes and pilot audience.','Interviewleitfaden, Kompetenz-Ausgangslage, Stakeholderkarte und abgestimmter Umfang. Gate: Ziele und Pilotgruppe bestätigt.','Görüşme rehberi, yetkinlik başlangıcı, paydaş haritası ve uzlaşılan kapsam. Kapı: sponsor hedefleri ve pilot kitleyi kabul eder.')],
 [T('Weeks 3–4','Woche 3–4','Hafta 3–4'),T('Design common core','Gemeinsamen Kern entwerfen','Ortak çekirdeği tasarla'),T('Journey, RACI, source register, operating model and first scenario. Gate: expert review dependency identified.','Lernreise, RACI, Quellenregister, Betriebsmodell und erstes Szenario. Gate: notwendige Fachprüfung festgelegt.','Yolculuk, RACI, kaynak kaydı, işletim modeli ve ilk senaryo. Kapı: uzman inceleme bağımlılığı belirlenir.')],
 [T('Weeks 5–6','Woche 5–6','Hafta 5–6'),T('Prototype & localise','Prototyp & Lokalisierung','Prototip ve yerelleştirme'),T('EN/DE/TR parity, facilitator guide and version controls. Gate: functional and language review.','EN/DE/TR-Parität, Dozentenleitfaden und Versionskontrolle. Gate: Funktions- und Sprachprüfung.','EN/DE/TR eşdeğerliği, eğitici rehberi ve sürüm kontrolleri. Kapı: işlev ve dil incelemesi.')],
 [T('Weeks 7–8','Woche 7–8','Hafta 7–8'),T('Pilot & evaluate','Pilotieren & evaluieren','Pilot ve değerlendir'),T('Usability sessions, observed task evidence, defect log and revised content. Gate: evidence supports limited rollout.','Nutzungstests, Aufgabenbeobachtung, Fehlerprotokoll und Inhaltsrevision. Gate: Nachweise stützen begrenzte Einführung.','Kullanılabilirlik oturumları, görev gözlemi, hata kaydı ve içerik düzeltmesi. Kapı: kanıt sınırlı yayılımı destekler.')],
 [T('Weeks 9–12','Woche 9–12','Hafta 9–12'),T('Roll out & improve','Einführen & verbessern','Yaygınlaştır ve iyileştir'),T('Train facilitators, release by region, monitor support and review outcomes. Gate: named service owner accepts handover.','Dozenten vorbereiten, regional freigeben, Support beobachten, Ergebnisse prüfen. Gate: benannte Verantwortung übernimmt.','Eğiticileri hazırla, bölgesel yayımla, desteği izle ve sonuçları incele. Kapı: adı belirli hizmet sahibi devri kabul eder.')]
 ],
 agile:T('Use a prioritised backlog and a weekly inspect-and-adapt cycle. Limit work in progress to two items. Ready means a clear user need, acceptance criteria and dependencies. Done means an implemented artefact, passing checks, evidence and a release note. A board alone is not Scrum; no Scrum Master certification or historic agile delivery is claimed.','Priorisierten Backlog und wöchentlichen Inspect-and-Adapt-Zyklus nutzen. Maximal zwei Aufgaben gleichzeitig. Ready: Bedarf, Akzeptanzkriterien und Abhängigkeiten klar. Done: Artefakt umgesetzt, Prüfungen bestanden, Nachweis und Versionshinweis vorhanden. Ein Board ist kein Scrum; keine Zertifizierung oder frühere agile Umsetzung wird behauptet.','Öncelikli backlog ve haftalık incele-uyarla döngüsü kullanılır. Aynı anda en fazla iki iş. Ready: ihtiyaç, kabul kriterleri ve bağımlılıklar açık. Done: çıktı uygulanmış, kontroller geçmiş, kanıt ve sürüm notu var. Pano tek başına Scrum değildir; Scrum Master sertifikası veya geçmiş agile deneyimi iddia edilmez.'),
 risks:[
 [T('No domain reviewer','Keine Fachprüfung','Uzman incelemesi yok'),T('High','Hoch','Yüksek'),T('Block domain release; recruit an authorised reviewer before a real pilot','Fachliche Freigabe sperren; vor realem Pilot autorisierte Prüfung organisieren','Alan içeriği yayınını durdur; gerçek pilot öncesi yetkili uzman bul')],
 [T('Unvalidated customer needs','Ungeprüfte Kundenbedarfe','Doğrulanmamış müşteri ihtiyacı'),T('High','Hoch','Yüksek'),T('Interview customers and service teams; revise problem statement','Kunden und Serviceteams interviewen; Problemdefinition überarbeiten','Müşteri ve servis ekipleriyle görüş; sorun tanımını düzelt')],
 [T('Translation drift','Übersetzungsabweichung','Çeviri kayması'),T('Medium','Mittel','Orta'),T('Stable objective IDs; regional terminology review; test all languages','Stabile Lernziel-IDs; regionale Terminologieprüfung; alle Sprachen testen','Sabit hedef kimlikleri; bölgesel terim incelemesi; tüm dilleri test et')],
 [T('Synthetic results mistaken for outcomes','Synthetische Daten als Ergebnis missverstanden','Sentetik verinin sonuç sanılması'),T('High','Hoch','Yüksek'),T('Label every dashboard and export; separate measured and proposed evidence','Alle Übersichten und Exporte kennzeichnen; gemessen und geplant trennen','Her panel ve dışa aktarımı etiketle; ölçülen ve planlanan kanıtı ayır')]
 ],
 evidence:[
 ['Educational strategy / business acumen',T('Business priorities, value assumptions and pilot gates','Geschäftsprioritäten, Nutzenannahmen und Pilot-Gates','İş öncelikleri, değer varsayımları ve pilot kapıları'),0],
 ['Global initiatives / Business Lines / Regional Organizations',T('Three learning contexts, regional ownership and shared standards','Drei Lernkontexte, regionale Verantwortung und gemeinsame Standards','Üç öğrenme bağlamı, bölgesel sahiplik ve ortak standartlar'),2],
 ['Customer Journey Mapping / Customer Success',T('Six-stage hypothesis map with touchpoints, owners and measures','Sechsstufige Hypothesenkarte mit Kontaktpunkten, Zuständigkeit und Messung','Temas noktası, sorumlu ve ölçümlü altı aşamalı varsayım haritası'),1],
 ['Process design / Operating models',T('Intake-to-improvement process and decision rights','Prozess von Anfrage bis Verbesserung und Entscheidungsrechte','Talepten iyileştirmeye süreç ve karar yetkileri'),2],
 ['Governance / standards / regulated context',T('Simulated source, expert, regional and QA release gates; no compliance certification','Simulierte Quellen-, Fach-, Regional- und QA-Freigaben; keine Compliance-Zertifizierung','Simüle kaynak, uzman, bölge ve kalite yayın kontrolleri; uygunluk sertifikası yok'),3],
 ['Digital / workforce-centric learning',T('Three branching cases with first-attempt evidence','Drei verzweigte Fälle mit Erstversuchsnachweisen','İlk deneme kanıtlı üç dallanan vaka'),4],
 ['Project management / agile ways of working',T('Notion backlog, acceptance criteria, dependencies and a proposed rollout','Notion-Backlog, Akzeptanzkriterien, Abhängigkeiten und vorgeschlagener Rollout','Notion backlog, kabul kriterleri, bağımlılıklar ve önerilen yaygınlaştırma'),6],
 ['Continuous improvement / analytical skills',T('Transparent denominators, pilot protocol, change request and rollback','Transparente Nenner, Pilotprotokoll, Änderungsantrag und Rücksetzung','Açık paydalar, pilot protokolü, değişiklik talebi ve geri dönüş'),5],
 ['Stakeholder collaboration / matrix coordination',T('Designed RACI and escalation; real stakeholder implementation still unproven','Entworfene RACI und Eskalation; reale Umsetzung mit Stakeholdern noch unbelegt','Tasarlanan RACI ve yönlendirme; gerçek paydaş uygulaması henüz kanıtlanmadı'),2],
 ['English / German / Turkish',T('Equivalent interface and project content in three languages; independent language review pending','Gleichwertige Oberfläche und Projektinhalte in drei Sprachen; unabhängige Sprachprüfung offen','Üç dilde eşdeğer arayüz ve proje içeriği; bağımsız dil incelemesi bekliyor'),7],
 ['Emerging trends / AI / immersive learning',T('Human oversight and source controls; VR and AI generation are roadmap options, not implemented claims','Menschliche Aufsicht und Quellenkontrolle; VR und KI-Generierung sind Optionen, keine umgesetzten Funktionen','İnsan gözetimi ve kaynak kontrolü; VR ve AI üretimi yol haritası seçeneği, uygulanmış özellik değil'),7]
 ],
 trends:T('Evaluate emerging approaches against a specific learning problem: source-grounded AI for resource discovery; immersive simulation for spatial tasks; hybrid coaching for transfer. Decision criteria: learning value, accessibility, maintenance cost, source traceability and human oversight. Current choice: lightweight decision simulation; no VR or autonomous AI is needed to test the initial workflow hypothesis.','Neue Ansätze am konkreten Lernproblem bewerten: quellengebundene KI für Ressourcensuche, immersive Simulation für räumliche Aufgaben, hybrides Coaching für Transfer. Kriterien: Lernnutzen, Barrierefreiheit, Wartungskosten, Nachvollziehbarkeit und menschliche Aufsicht. Aktuelle Wahl: schlanke Entscheidungssimulation; VR oder autonome KI sind für die erste Prozesshypothese nicht erforderlich.','Yeni yaklaşımları belirli öğrenme sorununa göre değerlendir: kaynak keşfi için kaynağa bağlı AI, mekânsal görevler için sürükleyici simülasyon, transfer için hibrit koçluk. Ölçütler: öğrenme değeri, erişilebilirlik, bakım maliyeti, kaynak izlenebilirliği ve insan gözetimi. Mevcut seçim: hafif karar simülasyonu; ilk süreç varsayımı için VR veya otonom AI gerekli değil.'),
 cv:T('Developed an independent EN/DE/TR service-education integration prototype, including customer-journey mapping, a target operating model, RACI, simulated release governance and a transparent capability-measurement dashboard; tracked implementation evidence in Notion and versioned the public site on GitHub.','Entwickelte einen unabhängigen EN/DE/TR-Prototyp zur Integration der Serviceweiterbildung mit Customer Journey Mapping, Zielbetriebsmodell, RACI, simulierter Freigabe-Governance und transparenter Kompetenzmessung; dokumentierte Umsetzungsnachweise in Notion und versionierte die öffentliche Website auf GitHub.','Customer Journey Mapping, hedef işletim modeli, RACI, simüle yayın yönetişimi ve şeffaf yetkinlik ölçüm paneli içeren bağımsız EN/DE/TR servis eğitimi entegrasyon prototipi geliştirdi; uygulama kanıtlarını Notion’da takip etti ve kamuya açık siteyi GitHub’da sürümledi.')
};
